---
# TODO
# Install spacemacs
# Install oh my zsh
# Use Alfred backup
# Configure Karabiner
# Configure keyboardmaestro
# Customize .osx


downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/andrewsanchez/dotfiles-plus.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/dotfiles-plus
dotfiles_files:
  - .bash_profile
  - .bash_aliases
  - .gitignore
  - .gitconfig
  - .spacemacs
  - .zshrc
  - .zsh_custom

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - bitwarden-cli
  - doxygen
  - emacs-plus
  - fd
  - git
  - gpg
  - htop
  - httpie
  - hub
  - ispell
  - miniconda 
  - node
  - openssl
  - pandoc
  - postgresql
  - readline
  - shellcheck
  - sqlite
  - ssh-copy-id
  - tree
  - wget
  - youtube-dl
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - d12frosted/emacs-plus

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - android-file-transfer
  - anki
  - bitwarden
  - copyq
  - discord
  - docker
  - dropbox
  - flux
  - font-source-code-pro
  - google-backup-and-sync
  - google-chrome
  - iterm2
  - karabiner-elements
  - keyboard-maestro
  - libreoffice
  - mactex
  - notion
  - pycharm
  - skype
  - slack
  - spotify
  - telegram
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - whatsapp
  - zoomus
  - zulip

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
